import {auth,db,isFirebaseConfigured} from './firebase.js';
import {signInWithEmailAndPassword,onAuthStateChanged,signOut} from 'https://www.gstatic.com/firebasejs/12.1.0/firebase-auth.js';
import {collection,getDocs,getDoc,query,where,orderBy,addDoc,doc,setDoc,deleteDoc,serverTimestamp,runTransaction} from 'https://www.gstatic.com/firebasejs/12.1.0/firebase-firestore.js';
import {monthCalendar,defaultSlots} from './calendar.js';

const els=id=>document.getElementById(id); const toast=t=>{els('toast').textContent=t;els('toast').classList.add('show');setTimeout(()=>els('toast').classList.remove('show'),2200)};
let adminUser=null, appointments=[];

if(!isFirebaseConfigured()){els('adminError').textContent='Firebase не настроен. Заполните js/firebase-config.js и опубликуйте заново.';els('adminLoginForm').querySelector('button').disabled=true;}


els('adminLoginForm').addEventListener('submit',async e=>{e.preventDefault();els('adminError').textContent='';try{if(!auth)throw new Error('Firebase не настроен');const cred=await signInWithEmailAndPassword(auth,els('adminEmail').value,els('adminPassword').value);const snap=await getDoc(doc(db,'admins',cred.user.uid));if(!snap.exists()){await signOut(auth);throw new Error('У этого аккаунта нет доступа к панели. Добавьте UID в коллекцию admins.');}adminUser=cred.user;els('adminGate').classList.add('hidden');els('adminApp').classList.remove('hidden');await loadAll();}catch(ex){els('adminError').textContent=ex.message;}});
els('adminLogout').onclick=()=>signOut(auth);

function setupTabs(){document.querySelectorAll('.admin-tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.admin-tabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('.admin-panel').forEach(x=>x.classList.add('hidden'));els('tab-'+b.dataset.tab).classList.remove('hidden');});}
async function loadAll(){setupTabs();els('adminDate').valueAsDate=new Date();await loadAppointments();await loadMasters();await loadServices();await loadReviews();renderMiniCalendar();}
async function loadAppointments(){if(!db)return;try{const snap=await getDocs(query(collection(db,'appointments'),orderBy('date','desc')));appointments=snap.docs.map(d=>({id:d.id,...d.data()}));}catch(e){console.warn(e);appointments=[];}renderAppointments();}
function renderAppointments(){const date=els('adminDate').value;const list=appointments.filter(a=>{const d=a.date?.toDate?a.date.toDate():new Date(a.date);return d.toISOString().slice(0,10)===date;}).sort((a,b)=>String(a.time).localeCompare(String(b.time)));els('appointmentsTable').innerHTML=`<div class="table-head"><span>Время</span><span>Клиент</span><span>Услуга</span><span>Мастер</span><span>Статус</span></div>${list.length?list.map(a=>`<div class="table-row"><b>${a.time||'—'}</b><span>${a.clientName||a.clientEmail||'—'}</span><span>${a.serviceName||'—'}</span><span>${a.masterName||'—'}</span><span><button class="status-pill" data-status="${a.id}">${a.status||'booked'}</button></span></div>`).join(''):'<div class="empty-state">На выбранную дату записей нет.</div>'}`;}
els('adminDate').addEventListener('change',renderAppointments);
function renderMiniCalendar(){monthCalendar({container:els('adminCalendar'),selected:new Date(),onSelect:d=>{els('adminDate').valueAsDate=d;renderAppointments();}});}

async function loadMasters(){if(!db)return;const snap=await getDocs(query(collection(db,'masters'),orderBy('name'))).catch(()=>({empty:true,docs:[]}));els('mastersAdmin').innerHTML=(snap.docs||[]).map(d=>({id:d.id,...d.data()})).map(m=>`<div class="admin-card"><div class="admin-avatar">${(m.name||'?')[0]}</div><div><h3>${m.name}</h3><p>${m.role||'Специалист'}</p><small>${m.bookingEnabled===false?'Онлайн-запись выключена':'Онлайн-запись включена'}</small></div><div class="card-actions"><button class="secondary" data-edit-master="${m.id}">Изменить</button><button class="danger" data-del-master="${m.id}">Удалить</button></div></div>`).join('')||'<div class="empty-state">Добавьте первого мастера.</div>';}
async function loadServices(){if(!db)return;const snap=await getDocs(query(collection(db,'services'),orderBy('name'))).catch(()=>({empty:true,docs:[]}));els('servicesAdmin').innerHTML=(snap.docs||[]).map(d=>({id:d.id,...d.data()})).map(s=>`<div class="admin-card"><div><h3>${s.name}</h3><p>${Number(s.price||0).toLocaleString('ru-RU')} ₽ · ${s.duration||0} мин.</p></div><div class="card-actions"><button class="secondary" data-edit-service="${s.id}">Изменить</button><button class="danger" data-del-service="${s.id}">Удалить</button></div></div>`).join('')||'<div class="empty-state">Добавьте первую услугу.</div>';}
async function loadReviews(){els('reviewsAdmin').innerHTML='<div class="admin-card"><div><h3>Пример отзыва</h3><p>Модерация отзывов подключается через коллекцию reviews.</p></div><span class="rating-badge">5.0 ★</span></div>';}

function openForm(title,fields,onSave){els('adminModalContent').innerHTML=`<div class="modal-title"><span class="eyebrow">УПРАВЛЕНИЕ</span><h2>${title}</h2></div><form id="entityForm" class="stack-form">${fields}<button class="primary full">Сохранить</button><div id="entityError" class="form-error"></div></form>`;els('adminModal').classList.add('open');els('entityForm').onsubmit=async e=>{e.preventDefault();try{await onSave();els('adminModal').classList.remove('open');toast('Сохранено ✅');await loadAll();}catch(ex){els('entityError').textContent=ex.message;}};}
els('addMaster').onclick=()=>openForm('Новый мастер','<label>Имя<input id="fName" required></label><label>Должность<input id="fRole" value="Мастер маникюра и педикюра"></label><label>Интервалы работы<input id="fHours" value="10:00–20:00"></label>',async()=>addDoc(collection(db,'masters'),{name:els('fName').value,role:els('fRole').value,hours:els('fHours').value,bookingEnabled:true,createdAt:serverTimestamp()}));
els('addService').onclick=()=>openForm('Новая услуга','<label>Название<input id="fName" required></label><label>Цена, ₽<input id="fPrice" type="number" required></label><label>Длительность, мин.<input id="fDuration" type="number" value="60" required></label>',async()=>addDoc(collection(db,'services'),{name:els('fName').value,price:Number(els('fPrice').value),duration:Number(els('fDuration').value),active:true,createdAt:serverTimestamp()}));
els('newAppointment').onclick=async()=>{
  let masters=[],services=[];
  if(db){masters=(await getDocs(query(collection(db,'masters'),orderBy('name')))).docs.map(d=>({id:d.id,...d.data()}));services=(await getDocs(query(collection(db,'services'),orderBy('name')))).docs.map(d=>({id:d.id,...d.data()}));}
  openForm('Запись от администратора',`<label>Имя клиента<input id="fName" required></label><label>Email клиента<input id="fEmail" type="email"></label><label>Мастер<select id="fMaster">${masters.map(m=>`<option value="${m.id}">${m.name}</option>`).join('')}</select></label><label>Услуга<select id="fService">${services.map(s=>`<option value="${s.id}">${s.name}</option>`).join('')}</select></label><label>Дата<input id="fDate" type="date" value="${new Date().toISOString().slice(0,10)}" required></label><label>Время<select id="fTime">${defaultSlots.map(t=>`<option>${t}</option>`).join('')}</select></label>`,async()=>{
    const m=masters.find(x=>x.id===els('fMaster').value)||{};const s=services.find(x=>x.id===els('fService').value)||{};
    const lockId=`${m.id}_${els('fDate').value}_${els('fTime').value.replace(':','-')}`;await runTransaction(db,async tx=>{const lockRef=doc(db,'slotLocks',lockId);const lock=await tx.get(lockRef);if(lock.exists())throw new Error('Это время уже занято.');const apptRef=doc(collection(db,'appointments'));tx.set(lockRef,{masterId:m.id||'',dateKey:els('fDate').value,time:els('fTime').value,taken:true,createdAt:serverTimestamp()});tx.set(apptRef,{clientName:els('fName').value,clientEmail:els('fEmail').value,masterId:m.id||'',masterName:m.name||'',serviceId:s.id||'',serviceName:s.name||'',price:Number(s.price||0),duration:Number(s.duration||0),dateKey:els('fDate').value,date:new Date(els('fDate').value+'T00:00:00'),time:els('fTime').value,status:'booked',createdBy:adminUser.uid,createdAt:serverTimestamp()});});
  });
};

document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>b.closest('.modal-backdrop').classList.remove('open'));
onAuthStateChanged(auth,u=>{if(!u){els('adminGate').classList.remove('hidden');els('adminApp').classList.add('hidden');}});

document.addEventListener('click',async e=>{
  const editM=e.target.closest('[data-edit-master]'); const delM=e.target.closest('[data-del-master]');
  const editS=e.target.closest('[data-edit-service]'); const delS=e.target.closest('[data-del-service]');
  if(editM){const id=editM.dataset.editMaster;const snap=await getDocs(query(collection(db,'masters'),where('__name__','==',id)));if(snap.empty)return;const m=snap.docs[0].data();openForm('Изменить мастера',`<label>Имя<input id="fName" value="${m.name||''}" required></label><label>Должность<input id="fRole" value="${m.role||''}"></label><label>Интервалы работы<input id="fHours" value="${m.hours||''}"></label>`,async()=>setDoc(doc(db,'masters',id),{name:els('fName').value,role:els('fRole').value,hours:els('fHours').value},{merge:true}));}
  if(delM&&confirm('Удалить мастера?')){await deleteDoc(doc(db,'masters',delM.dataset.delMaster));toast('Мастер удален');await loadAll();}
  if(editS){const id=editS.dataset.editService;const snap=await getDocs(query(collection(db,'services'),where('__name__','==',id)));if(snap.empty)return;const s=snap.docs[0].data();openForm('Изменить услугу',`<label>Название<input id="fName" value="${s.name||''}" required></label><label>Цена, ₽<input id="fPrice" type="number" value="${s.price||0}" required></label><label>Длительность, мин.<input id="fDuration" type="number" value="${s.duration||60}" required></label>`,async()=>setDoc(doc(db,'services',id),{name:els('fName').value,price:Number(els('fPrice').value),duration:Number(els('fDuration').value)},{merge:true}));}
  if(delS&&confirm('Удалить услугу?')){await deleteDoc(doc(db,'services',delS.dataset.delService));toast('Услуга удалена');await loadAll();}
});
